package webidl2;

import util.EitherType;

typedef ExtendedAttributeRightHandSideBase = EitherType<ExtendedAttributeRightHandSideIdentifier, ExtendedAttributeRightHandSideString, ExtendedAttributeRightHandSideDecimal, ExtendedAttributeRightHandSideInteger>;
