package webidl2;

import util.EitherType;

typedef ExtendedAttributeRightHandSideList = EitherType<ExtendedAttributeRightHandSideIdentifierList, ExtendedAttributeRightHandSideStringList, ExtendedAttributeRightHandSideDecimalList, ExtendedAttributeRightHandSideIntegerList>;
