package webidl2;

@:forward
abstract ValueDescription(AbstractValueDescription<Dynamic>)
from ValueDescriptionString
from ValueDescriptionNumber
from ValueDescriptionBoolean
from ValueDescriptionNull
from ValueDescriptionInfinity
from ValueDescriptionNaN
from ValueDescriptionSequence
from ValueDescriptionDictionary
{}
